/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;

/**
 *
 * @author Daan
 */
public class DefaultBtnPanel extends javax.swing.JPanel {

    /**
     * Creates new form DefaultBtnPanel
     */
    public DefaultBtnPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        incluirBtn = new javax.swing.JButton();
        excluirBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(80, 500));

        incluirBtn.setText("Incluir");

        excluirBtn.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(465, Short.MAX_VALUE)
                .addComponent(excluirBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incluirBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incluirBtn)
                    .addComponent(excluirBtn))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton excluirBtn;
    private javax.swing.JButton incluirBtn;
    // End of variables declaration//GEN-END:variables

    public JButton getExcluirBtn() {
        return excluirBtn;
    }

    public void setExcluirBtn(JButton excluirBtn) {
        this.excluirBtn = excluirBtn;
    }

    public JButton getIncluirBtn() {
        return incluirBtn;
    }

    public void setIncluirBtn(JButton incluirBtn) {
        this.incluirBtn = incluirBtn;
    }

    
}
